CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE reader_books (
    reader_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    PRIMARY KEY (reader_id, book_id),
    FOREIGN KEY (reader_id) REFERENCES readers(id),
    FOREIGN KEY (book_id) REFERENCES books(id)
);

INSERT INTO readers (name, email) VALUES
('Иван', 'ivan@example.com'),
('Мария', 'maria@example.com');

INSERT INTO reader_books (reader_id, book_id) VALUES
(1, 1),
(1, 2),
(2, 1);